[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "science-rag"
version = "0.1.0"
description = "science-rag"
requires-python = ">= 3.11"
maintainers = [
    { name = "ai", email = "ai@dbc.dk" }
]
dependencies = [
    "langchain-community",
    "langchain-unstructured",
    "langgraph",
    "streamlit",
    "scikit-learn",
    "numpy",
    "nltk>=3.10.3",
    "sentence_transformers>=6.1.0",
    "rich",
    "transformers",
    "torch",
    "fastapi",
    "uvicorn",
    "httpx",
    "openai",
    "requests",
    "accelerate",
    "faiss-cpu>=1.14.2",
]

[dependency-groups]
dev = [
    "docling",
    "pre-commit",
    "pytest",
    "ruff",
    "pip-audit",
]
dbc = [
    "dbc_pyutils",
]

[project.scripts]
create-faiss-index = "science_rag.rag.retrievers.indexes.multilinguale5:main"
streaming-service-science-rag = "science_rag.service.start:main"

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]


[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 120

[tool.uv]
constraint-dependencies = [
    "anyio>=4.15.1",
    "gitpython>=3.1.62",
]

[[tool.uv.index]]
name = "dbc-devpi"
url = "https://devpi.dbccloud.dk/dbc/packages/+simple/"
publish-url = "https://devpi.dbccloud.dk/dbc/packages"
